name: faith_connect
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:

    - assets/home.jpg
    - assets/today.jpg
    - assets/tomorrow.jpg
    - assets/wednesday.jpg
    - assets/thursday.jpg
    - assets/friday.jpg
    - assets/saturday.jpg
    - assets/sunday.jpg
    - assets/front.jpg
    - assets/reminders.jpg
    - assets/profile.jpg
    - assets/discover.jpg
    - assets/religious.jpg
    - assets/meditation.jpg
    - assets/reflection.jpg
    - assets/liturgicalbg.jpg
    - assets/thumbnail.jpg
    - assets/liturgicalSongs.jpg
    - assets/profiles.jpg
    
